import type { Json } from '../types/database'

export type PracticeMode='learn_alac'|'practice'
export type SourceTier='supreme_court'|'professor_supplied'|'institutional_suggested'
export type FindingCategory='run_on'|'missing_terminal_punctuation'|'tentative_phrasing'|'repeated_word'|'inconsistent_naming'|'missing_direct_answer'|'missing_legal_basis'|'inconsistent_conclusion'
export interface TextSpan { [key:string]:Json|undefined; start:number; end:number }
export interface PracticeFinding { [key:string]:Json|undefined; category:FindingCategory; span:TextSpan; message:string; severity:'info'|'warning' }
export interface RubricComponent { [key:string]:Json|undefined; maxPoints:number; evidenceRequirement:string }
export interface AnswerKey { [key:string]:Json|undefined; directAnswer:string; legalBasis:{authorities:string[];explanation:string}; application:string; conclusion:string; alternativeConclusions:{conclusion:string;conditions:string}[]; rubric:Record<'directAnswer'|'legalBasis'|'application'|'conclusion'|'legalWriting',RubricComponent>; commonErrors:string[] }
export interface PracticeQuestion { id:string; household_id:string; created_by:string; source_tier:SourceTier; bar_year:number; exam_date:string|null; subject:string; question_number:string; question_text:string; source_url:string; source_page:number|null; course_id:string|null; review_status:'unreviewed'|'reviewed'; locked:boolean; answer_key:AnswerKey; updated_at:string }
export interface PracticeAttempt { id:string; question_id:string; user_id:string; household_id:string; mode:PracticeMode; answer_direct:string|null; answer_legal_basis:string|null; answer_application:string|null; answer_conclusion:string|null; answer_freeform:string|null; alac_findings:PracticeFinding[]; writing_findings:PracticeFinding[]; submitted_at:string|null; revealed_early:boolean; is_benchmark:boolean }
export interface Feedback { id:string; attempt_id:string; grader_type:'self'|'partner'|'deterministic'|'ai'; grader_user_id:string|null; rubric_version:string; scores:Json; total_score:number; comments:Json; metadata?:Json }
export const emptyAnswerKey:AnswerKey={directAnswer:'',legalBasis:{authorities:[],explanation:''},application:'',conclusion:'',alternativeConclusions:[],rubric:{directAnswer:{maxPoints:.5,evidenceRequirement:'Direct response'},legalBasis:{maxPoints:1.5,evidenceRequirement:'Controlling rule'},application:{maxPoints:2,evidenceRequirement:'Facts applied to rule'},conclusion:{maxPoints:.5,evidenceRequirement:'Consistent result'},legalWriting:{maxPoints:.5,evidenceRequirement:'Clear legal writing'}},commonErrors:[]}
export function answerText(a:PracticeAttempt){return a.mode==='practice'?(a.answer_freeform??''):[a.answer_direct,a.answer_legal_basis,a.answer_application,a.answer_conclusion].filter(Boolean).join('\n\n')}
