/* oxlint-disable react/set-state-in-effect */
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabaseClient'
import { useAuth } from '../hooks/useAuth'
import { useHousehold } from '../hooks/useHousehold'
import { usePracticeAttempt } from '../hooks/usePracticeAttempt'
import { usePartnerComparison } from '../hooks/usePartnerComparison'
import { checkAlac } from '../lib/alacHeuristics'
import { checkWriting } from '../lib/writingChecks'
import { answerText, type PracticeMode, type PracticeQuestion } from '../lib/practiceTypes'
import { AlacEditor } from '../components/practice/AlacEditor'
import { BlankEditor } from '../components/practice/BlankEditor'
import { WritingFindingsPanel } from '../components/practice/WritingFindingsPanel'
import { SelfGradeForm } from '../components/practice/SelfGradeForm'
import { PartnerComparisonView } from '../components/practice/PartnerComparisonView'
import { VariationDiffView } from '../components/practice/VariationDiffView'

export function PracticeQuestion() {
  const { questionId } = useParams(); const { user } = useAuth(); const { householdId } = useHousehold()
  const [params] = useSearchParams(); const quickFire = params.get('quick') === '1'; const quickStarted = useRef(false)
  const [question, setQuestion] = useState<PracticeQuestion | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [parts, setParts] = useState({ direct: '', legalBasis: '', application: '', conclusion: '' }); const [free, setFree] = useState('')
  const { attempt, loading, start, reload } = usePracticeAttempt(questionId); const partner = usePartnerComparison(questionId)
  useEffect(() => { if (questionId) supabase.from('practice_questions').select('*').eq('id', questionId).single().then(({ data, error: loadError }) => { setQuestion(data as unknown as PracticeQuestion | null); setError(loadError?.message ?? '') }) }, [questionId])
  useEffect(() => { if (attempt) { setParts({ direct: attempt.answer_direct ?? '', legalBasis: attempt.answer_legal_basis ?? '', application: attempt.answer_application ?? '', conclusion: attempt.answer_conclusion ?? '' }); setFree(attempt.answer_freeform ?? '') } }, [attempt])
  useEffect(() => { if (!quickFire || quickStarted.current || loading || !question || question.review_status !== 'reviewed' || !householdId) return; quickStarted.current = true; start('practice', householdId).catch((caught) => setError(caught instanceof Error ? caught.message : 'Could not start Quick Fire.')) }, [quickFire, loading, question, householdId, start])
  useEffect(() => { if (!attempt || attempt.submitted_at) return; const timer = window.setTimeout(() => { supabase.from('practice_attempts').update({ answer_direct: parts.direct, answer_legal_basis: parts.legalBasis, answer_application: parts.application, answer_conclusion: parts.conclusion, answer_freeform: free, updated_at: new Date().toISOString() }).eq('id', attempt.id) }, 700); return () => window.clearTimeout(timer) }, [attempt, parts, free])
  const liveFindings = useMemo(() => checkAlac(parts), [parts])
  async function begin(mode: PracticeMode) { if (!householdId) return; try { await start(mode, householdId) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not start this attempt.') } }
  async function submit() { if (!attempt) return; const text = attempt.mode === 'practice' ? free : Object.values(parts).join('\n\n'); if (!text.trim()) { setError('Write an answer before submitting.'); return } setSaving(true); const { error: saveError } = await supabase.from('practice_attempts').update({ answer_direct: parts.direct, answer_legal_basis: parts.legalBasis, answer_application: parts.application, answer_conclusion: parts.conclusion, answer_freeform: free, alac_findings: checkAlac(parts), writing_findings: checkWriting(text), submitted_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('id', attempt.id); setSaving(false); if (saveError) { setError(`Your draft is still here. ${saveError.message}`); return } reload() }
  async function lock() { if (!question || !user || !window.confirm('Confirm that you verified the source, authorities, fact changes, and complete answer key. This locks the question.')) return; const { error: lockError } = await supabase.from('practice_questions').update({ review_status: 'reviewed', reviewed_by: user.id, reviewed_at: new Date().toISOString(), locked: true }).eq('id', question.id); if (lockError) { setError(lockError.message); return } setQuestion({ ...question, review_status: 'reviewed', locked: true }) }
  if (loading || !question) return <div className="p-6 text-sm text-ink-muted">{error || 'Loading…'}</div>
  const submitted = !!attempt?.submitted_at; const submittedText = attempt ? answerText(attempt) : ''
  return <main className="mx-auto max-w-4xl space-y-6 p-5 md:p-8">
    <Link to="/practice" className="text-sm text-ink-muted">← Practice</Link>
    {quickFire && <div className="rounded-full bg-accent-bg px-3 py-1 text-xs font-medium text-accent w-fit">Quick Fire</div>}
    <header><div className="flex flex-wrap gap-2 text-xs"><span className={`rounded-full px-2 py-1 ${question.kind === 'variation' ? 'bg-purple-100 text-purple-800' : 'bg-accent-bg text-accent'}`}>{question.kind === 'variation' ? 'Bar Question Variation' : 'Official Bar Question'}</span><span className="rounded-full bg-surface px-2 py-1">{question.review_status === 'reviewed' ? 'Reviewed' : 'Unreviewed draft'}</span></div><h1 className="mt-3 text-2xl font-semibold">{question.subject} · {question.bar_year} · Question {question.question_number}</h1><p className="mt-4 whitespace-pre-wrap leading-7">{question.question_text}</p>{question.kind === 'official' && <a href={question.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm text-accent">Open official source{question.source_page ? ` · page ${question.source_page}` : ''}</a>}{question.kind === 'variation' && <div className="mt-4"><VariationDiffView changes={question.fact_changes} />{question.parent_question_ids?.map((id) => <Link key={id} to={`/practice/${id}`} className="mr-3 mt-2 inline-block text-sm text-accent">Open parent question</Link>)}</div>}</header>
    {question.review_status === 'unreviewed' && <section className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-semibold">Review required</h2><p className="mt-1 text-sm">This draft cannot be practiced until a household member verifies and locks it.</p><button onClick={lock} className="mt-3 rounded-xl bg-amber-900 px-4 py-2 text-sm text-white">I verified it — approve & lock</button></section>}
    {question.review_status === 'reviewed' && !attempt && <section className="grid gap-3 sm:grid-cols-2"><Mode title="Guided Bar answer" body="Build one concise answer using the Supreme Court's direct answer, legal basis, application, and conclusion sequence." onClick={() => begin('learn_alac')} /><Mode title="Exam practice" body="Write one uninterrupted answer. Structural and grading feedback appears only after submission." onClick={() => begin('practice')} /></section>}
    {attempt && !submitted && <section className="space-y-4">{attempt.mode === 'learn_alac' ? <AlacEditor value={parts} onChange={setParts} findings={liveFindings} /> : <BlankEditor value={free} onChange={setFree} />}<p className="text-xs text-ink-muted">Draft changes save automatically.</p>{error && <p className="text-sm text-red-600">{error}</p>}<button onClick={submit} disabled={saving} className="rounded-xl bg-accent px-5 py-2.5 font-medium text-white">{saving ? 'Saving…' : 'Submit answer'}</button></section>}
    {attempt && submitted && user && <section className="space-y-6"><div className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-semibold">Reviewed answer key</h2><p className="mt-3"><b>Answer:</b> {question.answer_key.directAnswer}</p><p className="mt-2"><b>Legal basis:</b> {question.answer_key.legalBasis.explanation}</p><p className="mt-2"><b>Application:</b> {question.answer_key.application}</p><p className="mt-2"><b>Conclusion:</b> {question.answer_key.conclusion}</p></div><WritingFindingsPanel findings={attempt.writing_findings} /><SelfGradeForm attemptId={attempt.id} userId={user.id} answer={submittedText} answerKey={question.answer_key} onSaved={reload} />{quickFire && <Link to="/practice" className="inline-flex rounded-xl bg-accent px-5 py-2.5 font-medium text-white">Next Quick Fire question</Link>}<button onClick={async () => { await supabase.from('practice_attempts').update({ revealed_early: !attempt.revealed_early }).eq('id', attempt.id); reload() }} className="block text-sm text-accent">{attempt.revealed_early ? 'Keep private until partner submits' : 'Reveal to partner early'}</button><PartnerComparisonView mine={attempt} partner={partner.partnerAttempt} answerKey={question.answer_key} userId={user.id} feedback={partner.feedback} onChanged={partner.reload} /></section>}
  </main>
}
function Mode({ title, body, onClick }: { title: string; body: string; onClick: () => void }) { return <button onClick={onClick} className="rounded-2xl border border-border bg-surface p-6 text-left hover:border-accent"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-ink-muted">{body}</p></button> }
