import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import { formatCitation } from '../../lib/citations'
import { buildQuoteCitationDoc } from '../../lib/tiptapContent'

export function CreateLinkedNoteDialog({ readingId, readingTitle, page, quotedText, annotationId, sharedCourse, onClose }: { readingId: string; readingTitle: string; page: number; quotedText: string | null; annotationId: string | null; sharedCourse: boolean; onClose: () => void }) {
  const navigate = useNavigate(); const [title, setTitle] = useState(`${readingTitle} — p. ${page}`); const [visibility, setVisibility] = useState<'private' | 'shared'>(sharedCourse ? 'shared' : 'private'); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); const citation = formatCitation(readingTitle, page); const result = await supabase.rpc('create_reading_linked_note', { p_reading_item_id: readingId, p_page_number: page, p_quoted_text: quotedText, p_annotation_id: annotationId, p_title: title.trim() || `${readingTitle} — p. ${page}`, p_visibility: visibility, p_content: buildQuoteCitationDoc(quotedText, citation) }); if (result.error || !result.data) { setError(result.error?.message ?? 'Could not create note.'); setSaving(false); return } navigate(`/notes/${result.data}`) }
  return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/40 sm:items-center" onClick={() => { if (!saving) onClose() }}><form onSubmit={submit} onClick={(e) => e.stopPropagation()} className="w-full max-w-md space-y-3 rounded-t-2xl border border-border bg-surface p-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] sm:rounded-2xl"><h2 className="font-semibold text-navy">Create linked note</h2><p className="text-xs text-ink-muted">{readingTitle} · Page {page}</p>{quotedText && <blockquote className="max-h-24 overflow-auto rounded-lg bg-bg p-2 text-xs italic text-ink-muted">“{quotedText}”</blockquote>}{error && <p role="alert" className="rounded-lg bg-accent-bg p-2 text-sm text-accent">{error}</p>}<label className="block text-xs text-ink-muted">Note title<input autoFocus required value={title} onChange={(e) => setTitle(e.target.value)} className="mt-1 h-11 w-full rounded-lg border border-border bg-bg px-3 text-sm text-ink" /></label><div className="flex gap-1">{(['private','shared'] as const).map((value) => <button type="button" key={value} aria-pressed={visibility === value} onClick={() => setVisibility(value)} className={['min-h-11 rounded-lg px-3 capitalize', visibility === value ? 'bg-accent-bg text-accent' : 'bg-bg text-ink-muted'].join(' ')}>{value}</button>)}</div><div className="flex justify-end gap-2"><button type="button" disabled={saving} onClick={onClose} className="min-h-11 px-3 text-sm text-ink-muted">Cancel</button><button type="submit" disabled={saving} className="min-h-11 rounded-lg bg-accent px-4 text-sm font-medium text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create note'}</button></div></form></div>
}
