import { Link } from 'react-router-dom'
import type { ReaderViewMode } from '../../lib/readingTypes'

interface Props { courseId: string; title: string; courseName: string; sidebarOpen: boolean; viewMode: ReaderViewMode; bookmarked: boolean; rotation: number; onToggleSidebar: () => void; onViewMode: (mode: ReaderViewMode) => void; onBookmark: () => void; onNote: () => void; onPrint: () => void; onDownload: () => void; onFullscreen: () => void; onRotate: () => void }
export function ReaderToolbar(props: Props) {
  return <header className="flex min-h-[52px] shrink-0 items-center gap-1 border-b border-border bg-surface px-2 print:hidden md:px-3">
    <Link to={`/courses/${props.courseId}`} className="flex min-h-11 items-center rounded-lg px-2 text-ink-muted hover:bg-bg" aria-label="Back to course">←</Link>
    <button type="button" aria-expanded={props.sidebarOpen} onClick={props.onToggleSidebar} className="min-h-11 rounded-lg px-2 text-sm text-ink-muted hover:bg-bg">Panels</button>
    <div className="min-w-0 flex-1 px-1"><h1 className="truncate text-sm font-semibold text-navy">{props.title}</h1><p className="hidden truncate text-xs text-ink-muted sm:block">{props.courseName}</p></div>
    <div className="hidden items-center gap-1 sm:flex"><button type="button" onClick={() => props.onViewMode(props.viewMode === 'page' ? 'reflow' : 'page')} className="min-h-11 rounded-lg px-2 text-sm text-ink-muted hover:bg-bg">{props.viewMode === 'page' ? 'Reflow' : 'Pages'}</button><button type="button" aria-pressed={props.bookmarked} onClick={props.onBookmark} className={['min-h-11 rounded-lg px-2 text-sm', props.bookmarked ? 'bg-accent-bg text-accent' : 'text-ink-muted hover:bg-bg'].join(' ')}>Bookmark</button><button type="button" onClick={props.onNote} className="min-h-11 rounded-lg bg-accent px-3 text-sm font-medium text-white">+ Note</button></div>
    <details className="relative"><summary className="flex min-h-11 cursor-pointer list-none items-center rounded-lg px-2 text-sm text-ink-muted hover:bg-bg">More</summary><div className="absolute right-0 z-50 mt-1 w-48 rounded-xl border border-border bg-surface p-1.5 shadow-xl"><button type="button" onClick={() => props.onViewMode(props.viewMode === 'page' ? 'reflow' : 'page')} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg sm:hidden">{props.viewMode === 'page' ? 'Reflow view' : 'Page view'}</button><button type="button" onClick={props.onBookmark} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg sm:hidden">{props.bookmarked ? 'Remove bookmark' : 'Bookmark page'}</button><button type="button" onClick={props.onNote} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg sm:hidden">Create linked note</button><button type="button" onClick={props.onRotate} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg">Rotate {props.rotation}°</button><button type="button" onClick={props.onPrint} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg">Print original</button><button type="button" onClick={props.onDownload} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg">Download original</button>{document.fullscreenEnabled && <button type="button" onClick={props.onFullscreen} className="min-h-11 w-full rounded-lg px-3 text-left text-sm hover:bg-bg">Full screen</button>}</div></details>
  </header>
}
