import { useEffect, useState } from 'react'
import type { ExtractedPage } from '../../lib/readingTypes'

type Theme = 'light' | 'sepia' | 'dark'
export function ReflowView({ pages, loading, onOpenPage }: { pages: ExtractedPage[]; loading: boolean; onOpenPage: (page: number) => void }) {
  const [fontSize, setFontSize] = useState(() => Number(localStorage.getItem('a2:reflow-font')) || 18)
  const [lineHeight, setLineHeight] = useState(() => Number(localStorage.getItem('a2:reflow-line')) || 1.6)
  const [width, setWidth] = useState(() => Number(localStorage.getItem('a2:reflow-width')) || 760)
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('a2:reflow-theme') as Theme) || 'light')
  useEffect(() => { localStorage.setItem('a2:reflow-font', String(fontSize)); localStorage.setItem('a2:reflow-line', String(lineHeight)); localStorage.setItem('a2:reflow-width', String(width)); localStorage.setItem('a2:reflow-theme', theme) }, [fontSize, lineHeight, width, theme])
  const themeClass = theme === 'dark' ? 'bg-[#171a21] text-[#ece8e1]' : theme === 'sepia' ? 'bg-[#f4ecd8] text-[#3f3528]' : 'bg-surface text-ink'
  return <main className="min-h-0 flex-1 overflow-auto bg-black/10 p-3 md:p-6"><div className="sticky top-0 z-10 mx-auto mb-3 flex max-w-4xl flex-wrap gap-2 rounded-xl border border-border bg-surface p-2 text-xs shadow-sm"><select aria-label="Font size" value={fontSize} onChange={(e) => setFontSize(Number(e.target.value))} className="rounded border border-border bg-bg p-2">{[16,18,20,22,24].map((n) => <option key={n} value={n}>{n}px</option>)}</select><select aria-label="Line spacing" value={lineHeight} onChange={(e) => setLineHeight(Number(e.target.value))} className="rounded border border-border bg-bg p-2">{[1.4,1.6,1.8].map((n) => <option key={n} value={n}>{n} spacing</option>)}</select><select aria-label="Reading width" value={width} onChange={(e) => setWidth(Number(e.target.value))} className="rounded border border-border bg-bg p-2"><option value={640}>Narrow</option><option value={760}>Medium</option><option value={920}>Wide</option></select><select aria-label="Theme" value={theme} onChange={(e) => setTheme(e.target.value as Theme)} className="rounded border border-border bg-bg p-2"><option value="light">A2 light</option><option value="sepia">Sepia</option><option value="dark">Dark</option></select></div>
    <article className={`mx-auto rounded-xl px-5 py-8 shadow-sm md:px-10 ${themeClass}`} style={{ maxWidth: width, fontSize, lineHeight }}>{loading ? <p>Extracting text locally…</p> : pages.every((page) => !page.text) ? <p>This PDF has no extractable text. Read it in Page view.</p> : pages.map((page) => <section key={page.pageNumber} className="mb-10"><button type="button" onClick={() => onOpenPage(page.pageNumber)} className="mb-4 text-sm font-semibold text-accent">Page {page.pageNumber}</button>{page.blocks.map((block, i) => block.heading ? <h3 key={i} className="mb-3 mt-5 font-semibold">{block.text}</h3> : <p key={i} className="mb-3">{block.text}</p>)}</section>)}</article></main>
}
